/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappChannelRouteImport } from './routes/whatsapp-channel'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProductAgentLoginRouteImport } from './routes/product-agent-login'
import { Route as ProductAgentRouteImport } from './routes/product-agent'
import { Route as PiLoginRouteImport } from './routes/pi-login'
import { Route as PiRouteImport } from './routes/pi'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as JoinOurTeamRouteImport } from './routes/join-our-team'
import { Route as JoinAsProductAgentRouteImport } from './routes/join-as-product-agent'
import { Route as JoinAsIntroducerRouteImport } from './routes/join-as-introducer'
import { Route as JoinAsImplementerRouteImport } from './routes/join-as-implementer'
import { Route as ImplementerLoginRouteImport } from './routes/implementer-login'
import { Route as ImplementerRouteImport } from './routes/implementer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentLoginRouteImport } from './routes/agent-login'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountEditRouteImport } from './routes/account-edit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefCodeRouteImport } from './routes/ref.$code'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategoryIndustrialProductsIndexRouteImport } from './routes/category.industrial-products.index'
import { Route as CategoryIndustrialProductsSubRouteImport } from './routes/category.industrial-products.$sub'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa-callback'

const WhatsappChannelRoute = WhatsappChannelRouteImport.update({
  id: '/whatsapp-channel',
  path: '/whatsapp-channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductAgentLoginRoute = ProductAgentLoginRouteImport.update({
  id: '/product-agent-login',
  path: '/product-agent-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductAgentRoute = ProductAgentRouteImport.update({
  id: '/product-agent',
  path: '/product-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const PiLoginRoute = PiLoginRouteImport.update({
  id: '/pi-login',
  path: '/pi-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinOurTeamRoute = JoinOurTeamRouteImport.update({
  id: '/join-our-team',
  path: '/join-our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsProductAgentRoute = JoinAsProductAgentRouteImport.update({
  id: '/join-as-product-agent',
  path: '/join-as-product-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsIntroducerRoute = JoinAsIntroducerRouteImport.update({
  id: '/join-as-introducer',
  path: '/join-as-introducer',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsImplementerRoute = JoinAsImplementerRouteImport.update({
  id: '/join-as-implementer',
  path: '/join-as-implementer',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementerLoginRoute = ImplementerLoginRouteImport.update({
  id: '/implementer-login',
  path: '/implementer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementerRoute = ImplementerRouteImport.update({
  id: '/implementer',
  path: '/implementer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent-login',
  path: '/agent-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEditRoute = AccountEditRouteImport.update({
  id: '/account-edit',
  path: '/account-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndustrialProductsIndexRoute =
  CategoryIndustrialProductsIndexRouteImport.update({
    id: '/category/industrial-products/',
    path: '/category/industrial-products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryIndustrialProductsSubRoute =
  CategoryIndustrialProductsSubRouteImport.update({
    id: '/category/industrial-products/$sub',
    path: '/category/industrial-products/$sub',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa-callback',
  path: '/api/public/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-edit': typeof AccountEditRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-login': typeof AgentLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/implementer': typeof ImplementerRoute
  '/implementer-login': typeof ImplementerLoginRoute
  '/join-as-implementer': typeof JoinAsImplementerRoute
  '/join-as-introducer': typeof JoinAsIntroducerRoute
  '/join-as-product-agent': typeof JoinAsProductAgentRoute
  '/join-our-team': typeof JoinOurTeamRoute
  '/my-orders': typeof MyOrdersRoute
  '/pi': typeof PiRoute
  '/pi-login': typeof PiLoginRoute
  '/product-agent': typeof ProductAgentRoute
  '/product-agent-login': typeof ProductAgentLoginRoute
  '/shop': typeof ShopRoute
  '/whatsapp-channel': typeof WhatsappChannelRoute
  '/product/$id': typeof ProductIdRoute
  '/ref/$code': typeof RefCodeRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/category/industrial-products/$sub': typeof CategoryIndustrialProductsSubRoute
  '/category/industrial-products/': typeof CategoryIndustrialProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-edit': typeof AccountEditRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-login': typeof AgentLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/implementer': typeof ImplementerRoute
  '/implementer-login': typeof ImplementerLoginRoute
  '/join-as-implementer': typeof JoinAsImplementerRoute
  '/join-as-introducer': typeof JoinAsIntroducerRoute
  '/join-as-product-agent': typeof JoinAsProductAgentRoute
  '/join-our-team': typeof JoinOurTeamRoute
  '/my-orders': typeof MyOrdersRoute
  '/pi': typeof PiRoute
  '/pi-login': typeof PiLoginRoute
  '/product-agent': typeof ProductAgentRoute
  '/product-agent-login': typeof ProductAgentLoginRoute
  '/shop': typeof ShopRoute
  '/whatsapp-channel': typeof WhatsappChannelRoute
  '/product/$id': typeof ProductIdRoute
  '/ref/$code': typeof RefCodeRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/category/industrial-products/$sub': typeof CategoryIndustrialProductsSubRoute
  '/category/industrial-products': typeof CategoryIndustrialProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-edit': typeof AccountEditRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/agent-login': typeof AgentLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/implementer': typeof ImplementerRoute
  '/implementer-login': typeof ImplementerLoginRoute
  '/join-as-implementer': typeof JoinAsImplementerRoute
  '/join-as-introducer': typeof JoinAsIntroducerRoute
  '/join-as-product-agent': typeof JoinAsProductAgentRoute
  '/join-our-team': typeof JoinOurTeamRoute
  '/my-orders': typeof MyOrdersRoute
  '/pi': typeof PiRoute
  '/pi-login': typeof PiLoginRoute
  '/product-agent': typeof ProductAgentRoute
  '/product-agent-login': typeof ProductAgentLoginRoute
  '/shop': typeof ShopRoute
  '/whatsapp-channel': typeof WhatsappChannelRoute
  '/product/$id': typeof ProductIdRoute
  '/ref/$code': typeof RefCodeRoute
  '/api/public/mpesa-callback': typeof ApiPublicMpesaCallbackRoute
  '/category/industrial-products/$sub': typeof CategoryIndustrialProductsSubRoute
  '/category/industrial-products/': typeof CategoryIndustrialProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-edit'
    | '/admin'
    | '/agent'
    | '/agent-login'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/implementer'
    | '/implementer-login'
    | '/join-as-implementer'
    | '/join-as-introducer'
    | '/join-as-product-agent'
    | '/join-our-team'
    | '/my-orders'
    | '/pi'
    | '/pi-login'
    | '/product-agent'
    | '/product-agent-login'
    | '/shop'
    | '/whatsapp-channel'
    | '/product/$id'
    | '/ref/$code'
    | '/api/public/mpesa-callback'
    | '/category/industrial-products/$sub'
    | '/category/industrial-products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-edit'
    | '/admin'
    | '/agent'
    | '/agent-login'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/implementer'
    | '/implementer-login'
    | '/join-as-implementer'
    | '/join-as-introducer'
    | '/join-as-product-agent'
    | '/join-our-team'
    | '/my-orders'
    | '/pi'
    | '/pi-login'
    | '/product-agent'
    | '/product-agent-login'
    | '/shop'
    | '/whatsapp-channel'
    | '/product/$id'
    | '/ref/$code'
    | '/api/public/mpesa-callback'
    | '/category/industrial-products/$sub'
    | '/category/industrial-products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-edit'
    | '/admin'
    | '/agent'
    | '/agent-login'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/implementer'
    | '/implementer-login'
    | '/join-as-implementer'
    | '/join-as-introducer'
    | '/join-as-product-agent'
    | '/join-our-team'
    | '/my-orders'
    | '/pi'
    | '/pi-login'
    | '/product-agent'
    | '/product-agent-login'
    | '/shop'
    | '/whatsapp-channel'
    | '/product/$id'
    | '/ref/$code'
    | '/api/public/mpesa-callback'
    | '/category/industrial-products/$sub'
    | '/category/industrial-products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountEditRoute: typeof AccountEditRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ImplementerRoute: typeof ImplementerRoute
  ImplementerLoginRoute: typeof ImplementerLoginRoute
  JoinAsImplementerRoute: typeof JoinAsImplementerRoute
  JoinAsIntroducerRoute: typeof JoinAsIntroducerRoute
  JoinAsProductAgentRoute: typeof JoinAsProductAgentRoute
  JoinOurTeamRoute: typeof JoinOurTeamRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PiRoute: typeof PiRoute
  PiLoginRoute: typeof PiLoginRoute
  ProductAgentRoute: typeof ProductAgentRoute
  ProductAgentLoginRoute: typeof ProductAgentLoginRoute
  ShopRoute: typeof ShopRoute
  WhatsappChannelRoute: typeof WhatsappChannelRoute
  ProductIdRoute: typeof ProductIdRoute
  RefCodeRoute: typeof RefCodeRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
  CategoryIndustrialProductsSubRoute: typeof CategoryIndustrialProductsSubRoute
  CategoryIndustrialProductsIndexRoute: typeof CategoryIndustrialProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-channel': {
      id: '/whatsapp-channel'
      path: '/whatsapp-channel'
      fullPath: '/whatsapp-channel'
      preLoaderRoute: typeof WhatsappChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-agent-login': {
      id: '/product-agent-login'
      path: '/product-agent-login'
      fullPath: '/product-agent-login'
      preLoaderRoute: typeof ProductAgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-agent': {
      id: '/product-agent'
      path: '/product-agent'
      fullPath: '/product-agent'
      preLoaderRoute: typeof ProductAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi-login': {
      id: '/pi-login'
      path: '/pi-login'
      fullPath: '/pi-login'
      preLoaderRoute: typeof PiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-our-team': {
      id: '/join-our-team'
      path: '/join-our-team'
      fullPath: '/join-our-team'
      preLoaderRoute: typeof JoinOurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-product-agent': {
      id: '/join-as-product-agent'
      path: '/join-as-product-agent'
      fullPath: '/join-as-product-agent'
      preLoaderRoute: typeof JoinAsProductAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-introducer': {
      id: '/join-as-introducer'
      path: '/join-as-introducer'
      fullPath: '/join-as-introducer'
      preLoaderRoute: typeof JoinAsIntroducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-implementer': {
      id: '/join-as-implementer'
      path: '/join-as-implementer'
      fullPath: '/join-as-implementer'
      preLoaderRoute: typeof JoinAsImplementerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementer-login': {
      id: '/implementer-login'
      path: '/implementer-login'
      fullPath: '/implementer-login'
      preLoaderRoute: typeof ImplementerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementer': {
      id: '/implementer'
      path: '/implementer'
      fullPath: '/implementer'
      preLoaderRoute: typeof ImplementerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-login': {
      id: '/agent-login'
      path: '/agent-login'
      fullPath: '/agent-login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-edit': {
      id: '/account-edit'
      path: '/account-edit'
      fullPath: '/account-edit'
      preLoaderRoute: typeof AccountEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/industrial-products/': {
      id: '/category/industrial-products/'
      path: '/category/industrial-products'
      fullPath: '/category/industrial-products/'
      preLoaderRoute: typeof CategoryIndustrialProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/industrial-products/$sub': {
      id: '/category/industrial-products/$sub'
      path: '/category/industrial-products/$sub'
      fullPath: '/category/industrial-products/$sub'
      preLoaderRoute: typeof CategoryIndustrialProductsSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa-callback': {
      id: '/api/public/mpesa-callback'
      path: '/api/public/mpesa-callback'
      fullPath: '/api/public/mpesa-callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountEditRoute: AccountEditRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AgentLoginRoute: AgentLoginRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ImplementerRoute: ImplementerRoute,
  ImplementerLoginRoute: ImplementerLoginRoute,
  JoinAsImplementerRoute: JoinAsImplementerRoute,
  JoinAsIntroducerRoute: JoinAsIntroducerRoute,
  JoinAsProductAgentRoute: JoinAsProductAgentRoute,
  JoinOurTeamRoute: JoinOurTeamRoute,
  MyOrdersRoute: MyOrdersRoute,
  PiRoute: PiRoute,
  PiLoginRoute: PiLoginRoute,
  ProductAgentRoute: ProductAgentRoute,
  ProductAgentLoginRoute: ProductAgentLoginRoute,
  ShopRoute: ShopRoute,
  WhatsappChannelRoute: WhatsappChannelRoute,
  ProductIdRoute: ProductIdRoute,
  RefCodeRoute: RefCodeRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
  CategoryIndustrialProductsSubRoute: CategoryIndustrialProductsSubRoute,
  CategoryIndustrialProductsIndexRoute: CategoryIndustrialProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
